// 根据用户输入的位置进行定位(手动定位)

export const FETCH_LOCATION_BY_INPUT_START =
  'LOCATION/FETCH_LOCATION_BY_INPUT_START'

export const FETCH_LOCATION_BY_INPUT_SUCCESS =
  'LOCATION/FETCH_LOCATION_BY_INPUT_SUCCESS'

export const FETCH_LOCATION_BY_INPUT_FAILURE =
  'LOCATION/FETCH_LOCATION_BY_INPUT_FAILURE'
